//! # Conversation Session Manager
//!
//! Manages multi-turn conversation sessions with full CRUD, context windowing,
//! and automatic summarisation when token budgets are exceeded.
//!
//! ## Overview
//!
//! [`SessionManager`] stores sessions in a lock-free [`DashMap`], assigning
//! each a unique `u64` ID.  Each [`Session`] holds an ordered list of
//! [`Message`]s with per-message token counts.  Context retrieval trims the
//! oldest non-system messages to stay within a caller-supplied token budget.
//!
//! ## Example
//!
//! ```rust
//! use tokio_prompt_orchestrator::session_mgr::{SessionManager, Role};
//!
//! # #[tokio::main]
//! # async fn main() {
//! let mgr = SessionManager::default();
//! let id = mgr.create(Some("You are a helpful assistant.".into()));
//! mgr.append(id, Role::User, "Hello!".into()).unwrap();
//! let ctx = mgr.get_context(id, 4096).unwrap();
//! assert_eq!(ctx.len(), 2); // system + user
//! # }
//! ```

use chrono::{DateTime, Utc};
use dashmap::DashMap;
use std::collections::HashMap;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;
use thiserror::Error;

// ============================================================================
// Error type
// ============================================================================

/// Errors produced by [`SessionManager`] operations.
#[derive(Debug, Error, Clone, PartialEq, Eq)]
pub enum SessionError {
    /// The requested session ID does not exist.
    #[error("session {0} not found")]
    NotFound(u64),
}

// ============================================================================
// Domain types
// ============================================================================

/// The speaker role of a conversation message.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum Role {
    /// A system-level instruction prepended to the conversation.
    System,
    /// A message sent by the human user.
    User,
    /// A reply generated by the AI assistant.
    Assistant,
}

/// A single message within a [`Session`].
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Message {
    /// Who produced this message.
    pub role: Role,
    /// Raw text content.
    pub content: String,
    /// Wall-clock time when the message was appended.
    pub timestamp: DateTime<Utc>,
    /// Estimated token count, if known.
    pub tokens: Option<u32>,
}

impl Message {
    /// Best-effort token count: use provided value or fall back to word count.
    fn effective_tokens(&self) -> usize {
        self.tokens
            .map(|t| t as usize)
            .unwrap_or_else(|| self.content.split_whitespace().count())
    }
}

/// A conversation session holding an ordered sequence of [`Message`]s.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Session {
    /// Unique numeric identifier.
    pub id: u64,
    /// When this session was first created.
    pub created_at: DateTime<Utc>,
    /// Ordered message history (system message, if present, is always first).
    pub messages: Vec<Message>,
    /// Arbitrary key-value metadata attached by the caller.
    pub metadata: HashMap<String, String>,
}

impl Session {
    /// Total estimated token count across all messages.
    pub fn total_tokens(&self) -> usize {
        self.messages.iter().map(|m| m.effective_tokens()).sum()
    }
}

// ============================================================================
// Stats
// ============================================================================

/// Aggregate statistics across all sessions in a [`SessionManager`].
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct SessionStats {
    /// Number of sessions currently stored.
    pub total_sessions: usize,
    /// Alias for `total_sessions` (all stored sessions are considered active).
    pub active_sessions: usize,
    /// Mean message count across all sessions.
    pub avg_messages_per_session: f64,
    /// Sum of message counts across all sessions.
    pub total_messages: usize,
}

// ============================================================================
// SessionManager
// ============================================================================

/// Concurrent, lock-free store of [`Session`]s keyed by `u64` ID.
///
/// All methods are `&self` and safe to call from multiple Tokio tasks.
#[derive(Debug, Clone)]
pub struct SessionManager {
    sessions: Arc<DashMap<u64, Session>>,
    next_id: Arc<AtomicU64>,
}

impl Default for SessionManager {
    fn default() -> Self {
        Self {
            sessions: Arc::new(DashMap::new()),
            next_id: Arc::new(AtomicU64::new(1)),
        }
    }
}

impl SessionManager {
    /// Create a new manager with an empty store.
    pub fn new() -> Self {
        Self::default()
    }

    /// Create a new session, optionally pre-loading a system message.
    ///
    /// Returns the new session's ID.
    pub fn create(&self, system_prompt: Option<String>) -> u64 {
        let id = self.next_id.fetch_add(1, Ordering::Relaxed);
        let mut messages = Vec::new();
        if let Some(prompt) = system_prompt {
            let tokens = prompt.split_whitespace().count() as u32;
            messages.push(Message {
                role: Role::System,
                content: prompt,
                timestamp: Utc::now(),
                tokens: Some(tokens),
            });
        }
        let session = Session {
            id,
            created_at: Utc::now(),
            messages,
            metadata: HashMap::new(),
        };
        self.sessions.insert(id, session);
        id
    }

    /// Append a message to an existing session.
    ///
    /// Token count is estimated as word count when not supplied.
    pub fn append(
        &self,
        session_id: u64,
        role: Role,
        content: String,
    ) -> Result<(), SessionError> {
        let mut entry = self
            .sessions
            .get_mut(&session_id)
            .ok_or(SessionError::NotFound(session_id))?;
        let tokens = content.split_whitespace().count() as u32;
        entry.messages.push(Message {
            role,
            content,
            timestamp: Utc::now(),
            tokens: Some(tokens),
        });
        Ok(())
    }

    /// Return a copy of the session, or `Err(SessionError::NotFound)`.
    pub fn get(&self, session_id: u64) -> Result<Session, SessionError> {
        self.sessions
            .get(&session_id)
            .map(|r| r.clone())
            .ok_or(SessionError::NotFound(session_id))
    }

    /// Delete a session, returning `true` if it existed.
    pub fn delete(&self, session_id: u64) -> bool {
        self.sessions.remove(&session_id).is_some()
    }

    /// Return messages for a session trimmed to fit within `max_tokens`.
    ///
    /// Strategy:
    /// 1. The system message (if any) is always retained.
    /// 2. Non-system messages are trimmed from the **oldest** end until the
    ///    total fits within `max_tokens`.
    pub fn get_context(
        &self,
        session_id: u64,
        max_tokens: usize,
    ) -> Result<Vec<Message>, SessionError> {
        let session = self
            .sessions
            .get(&session_id)
            .ok_or(SessionError::NotFound(session_id))?;

        // Partition: system vs non-system
        let mut system: Vec<Message> = session
            .messages
            .iter()
            .filter(|m| m.role == Role::System)
            .cloned()
            .collect();
        let non_system: Vec<Message> = session
            .messages
            .iter()
            .filter(|m| m.role != Role::System)
            .cloned()
            .collect();

        let system_tokens: usize = system.iter().map(|m| m.effective_tokens()).sum();
        let budget = max_tokens.saturating_sub(system_tokens);

        // Walk non-system from newest to oldest, accumulating until full.
        let mut kept: Vec<Message> = Vec::new();
        let mut used = 0usize;
        for msg in non_system.iter().rev() {
            let t = msg.effective_tokens();
            if used + t > budget {
                break;
            }
            used += t;
            kept.push(msg.clone());
        }
        kept.reverse();
        system.extend(kept);
        Ok(system)
    }

    /// If the session's total tokens exceed `threshold_tokens`, call
    /// `summarizer` on the oldest non-system messages and replace them with a
    /// single assistant summary message.
    pub fn summarize_if_needed(
        &self,
        session_id: u64,
        threshold_tokens: usize,
        summarizer: &dyn Fn(&str) -> String,
    ) -> Result<(), SessionError> {
        let total = {
            let s = self
                .sessions
                .get(&session_id)
                .ok_or(SessionError::NotFound(session_id))?;
            s.total_tokens()
        };

        if total <= threshold_tokens {
            return Ok(());
        }

        let mut entry = self
            .sessions
            .get_mut(&session_id)
            .ok_or(SessionError::NotFound(session_id))?;

        // Separate system messages from the rest.
        let (system_msgs, non_system): (Vec<Message>, Vec<Message>) = entry
            .messages
            .drain(..)
            .partition(|m| m.role == Role::System);

        // Summarise the non-system portion.
        let combined: String = non_system
            .iter()
            .map(|m| format!("{:?}: {}", m.role, m.content))
            .collect::<Vec<_>>()
            .join("\n");
        let summary = summarizer(&combined);
        let summary_tokens = summary.split_whitespace().count() as u32;
        let summary_msg = Message {
            role: Role::Assistant,
            content: summary,
            timestamp: Utc::now(),
            tokens: Some(summary_tokens),
        };

        entry.messages = system_msgs;
        entry.messages.push(summary_msg);
        Ok(())
    }

    /// Collect aggregate statistics across all stored sessions.
    pub fn stats(&self) -> SessionStats {
        let total_sessions = self.sessions.len();
        let total_messages: usize = self.sessions.iter().map(|r| r.messages.len()).sum();
        let avg_messages_per_session = if total_sessions == 0 {
            0.0
        } else {
            total_messages as f64 / total_sessions as f64
        };
        SessionStats {
            total_sessions,
            active_sessions: total_sessions,
            avg_messages_per_session,
            total_messages,
        }
    }
}

// ============================================================================
// Unit tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    fn mgr() -> SessionManager {
        SessionManager::new()
    }

    // --- create ---

    #[test]
    fn test_create_no_system() {
        let m = mgr();
        let id = m.create(None);
        let s = m.get(id).unwrap();
        assert!(s.messages.is_empty());
    }

    #[test]
    fn test_create_with_system() {
        let m = mgr();
        let id = m.create(Some("sys".into()));
        let s = m.get(id).unwrap();
        assert_eq!(s.messages.len(), 1);
        assert_eq!(s.messages[0].role, Role::System);
    }

    #[test]
    fn test_create_returns_unique_ids() {
        let m = mgr();
        let a = m.create(None);
        let b = m.create(None);
        assert_ne!(a, b);
    }

    #[test]
    fn test_create_increments_ids() {
        let m = mgr();
        let a = m.create(None);
        let b = m.create(None);
        assert!(b > a);
    }

    // --- append ---

    #[test]
    fn test_append_ok() {
        let m = mgr();
        let id = m.create(None);
        assert!(m.append(id, Role::User, "hello".into()).is_ok());
    }

    #[test]
    fn test_append_not_found() {
        let m = mgr();
        let err = m.append(99, Role::User, "x".into()).unwrap_err();
        assert_eq!(err, SessionError::NotFound(99));
    }

    #[test]
    fn test_append_multiple_roles() {
        let m = mgr();
        let id = m.create(Some("sys".into()));
        m.append(id, Role::User, "q".into()).unwrap();
        m.append(id, Role::Assistant, "a".into()).unwrap();
        let s = m.get(id).unwrap();
        assert_eq!(s.messages.len(), 3);
    }

    // --- delete ---

    #[test]
    fn test_delete_existing() {
        let m = mgr();
        let id = m.create(None);
        assert!(m.delete(id));
    }

    #[test]
    fn test_delete_missing() {
        let m = mgr();
        assert!(!m.delete(999));
    }

    #[test]
    fn test_delete_removes_session() {
        let m = mgr();
        let id = m.create(None);
        m.delete(id);
        assert!(m.get(id).is_err());
    }

    // --- get_context ---

    #[test]
    fn test_get_context_not_found() {
        let m = mgr();
        assert!(m.get_context(0, 100).is_err());
    }

    #[test]
    fn test_get_context_all_fit() {
        let m = mgr();
        let id = m.create(Some("sys".into()));
        m.append(id, Role::User, "hello world".into()).unwrap();
        // 1 (sys) + 2 (user) = 3 tokens — well within budget
        let ctx = m.get_context(id, 100).unwrap();
        assert_eq!(ctx.len(), 2);
    }

    #[test]
    fn test_get_context_trims_oldest() {
        let m = mgr();
        let id = m.create(None);
        // Add 10 messages of ~10 words each → 100 tokens total
        for i in 0..10u32 {
            m.append(
                id,
                Role::User,
                format!("word1 word2 word3 word4 word5 word6 word7 word8 word9 word{i}"),
            )
            .unwrap();
        }
        // Budget only allows the last few messages
        let ctx = m.get_context(id, 25).unwrap();
        assert!(ctx.len() < 10, "should have trimmed some old messages");
    }

    #[test]
    fn test_get_context_always_keeps_system() {
        let m = mgr();
        let id = m.create(Some("system prompt here".into()));
        for _ in 0..20 {
            m.append(id, Role::User, "a b c d e f g h i j".into())
                .unwrap();
        }
        let ctx = m.get_context(id, 5).unwrap();
        // System message should be present even if nothing else fits
        assert!(ctx.iter().any(|msg| msg.role == Role::System));
    }

    #[test]
    fn test_get_context_zero_budget() {
        let m = mgr();
        let id = m.create(Some("sys".into()));
        m.append(id, Role::User, "hi".into()).unwrap();
        // Zero budget — only system can survive
        let ctx = m.get_context(id, 0).unwrap();
        assert!(ctx.iter().all(|msg| msg.role == Role::System));
    }

    // --- summarize_if_needed ---

    #[test]
    fn test_summarize_no_op_below_threshold() {
        let m = mgr();
        let id = m.create(Some("sys".into()));
        m.append(id, Role::User, "hi".into()).unwrap();
        m.summarize_if_needed(id, 10_000, &|text| format!("SUMMARY: {}", &text[..10.min(text.len())]))
            .unwrap();
        // Unchanged
        assert_eq!(m.get(id).unwrap().messages.len(), 2);
    }

    #[test]
    fn test_summarize_triggers_above_threshold() {
        let m = mgr();
        let id = m.create(Some("system".into()));
        for _ in 0..50 {
            m.append(id, Role::User, "a b c d e f g h".into()).unwrap();
        }
        let before = m.get(id).unwrap().messages.len();
        m.summarize_if_needed(id, 10, &|_| "Summary text".into())
            .unwrap();
        let after = m.get(id).unwrap().messages.len();
        assert!(after < before, "should have condensed messages");
    }

    #[test]
    fn test_summarize_not_found() {
        let m = mgr();
        let result = m.summarize_if_needed(999, 100, &|_| "s".into());
        assert!(result.is_err());
    }

    // --- stats ---

    #[test]
    fn test_stats_empty() {
        let m = mgr();
        let s = m.stats();
        assert_eq!(s.total_sessions, 0);
        assert_eq!(s.total_messages, 0);
        assert_eq!(s.avg_messages_per_session, 0.0);
    }

    #[test]
    fn test_stats_counts() {
        let m = mgr();
        let id1 = m.create(None);
        let id2 = m.create(None);
        m.append(id1, Role::User, "a".into()).unwrap();
        m.append(id1, Role::User, "b".into()).unwrap();
        m.append(id2, Role::User, "c".into()).unwrap();
        let s = m.stats();
        assert_eq!(s.total_sessions, 2);
        assert_eq!(s.total_messages, 3);
        assert!((s.avg_messages_per_session - 1.5).abs() < f64::EPSILON);
    }

    #[test]
    fn test_stats_active_equals_total() {
        let m = mgr();
        m.create(None);
        let s = m.stats();
        assert_eq!(s.active_sessions, s.total_sessions);
    }

    // --- clone / Arc sharing ---

    #[test]
    fn test_clone_shares_state() {
        let m1 = mgr();
        let m2 = m1.clone();
        let id = m1.create(None);
        // m2 sees the session created by m1
        assert!(m2.get(id).is_ok());
    }

    #[test]
    fn test_concurrent_creates_unique() {
        let m = mgr();
        let ids: Vec<u64> = (0..100).map(|_| m.create(None)).collect();
        let mut sorted = ids.clone();
        sorted.sort_unstable();
        sorted.dedup();
        assert_eq!(sorted.len(), 100);
    }
}
